@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

enum AnsiColors << enumeration >> {
  - AnsiColors(String): 
  + GREEN: 
  + CYAN: 
  + BLACK_BACKGROUND: 
  + GREEN_BACKGROUND: 
  + YELLOW_BACKGROUND: 
  + RESET: 
  + RED_BACKGROUND: 
  + PURPLE_BACKGROUND: 
  + BLUE_BACKGROUND: 
  + BLACK: 
  - code: String
  + PURPLE: 
  + WHITE: 
  + BLUE: 
  + WHITE_BACKGROUND: 
  + CYAN_BACKGROUND: 
  + YELLOW: 
  + RED: 
}
class App {
  + App(): 
}
class AppTest {
  + AppTest(String): 
}
class ArrayUtils {
  + ArrayUtils(): 
}
class Calculadora {
  + Calculadora(): 
}
class Controller {
  + Controller(): 
}
class FileReader {
  + FileReader(String): 
  ~ objReader: BufferedReader
  ~ strCurrentLine: String
}
class ICalculadora {
  + ICalculadora(): 
}
interface ICalculator << interface >>
class InvertedMinAndMaxBoundException {
  + InvertedMinAndMaxBoundException(): 
  + InvertedMinAndMaxBoundException(String): 
}
class Menu {
  + Menu(): 
  - selectedIndex: int
  - footerColors: AnsiColors[]
  - entriesColors: AnsiColors[]
  - footer: String
  - header: String
  - headerColors: AnsiColors[]
  - indexColors: AnsiColors[]
  - entries: List<MenuEntry>
}
class MenuEntry<T> {
  + MenuEntry(T, Function<T, String>, Predicate<T>): 
  + MenuEntry(T, Function<T, String>): 
  + MenuEntry(String, T, Predicate<T>): 
  + MenuEntry(T): 
  - observerFunction: Predicate<T>
  - prompt: String
  - observedObject: T
}
class MostrarMenu {
  + MostrarMenu(): 
  ~ vista: Vista
  ~ opcion: int
  ~ controlador: Controller
}
class PostFixValidator {
  + PostFixValidator(): 
  - expression: String
}
class Printer {
  + Printer(): 
}
class ProgressBar {
  + ProgressBar(): 
}
class Random {
  + Random(): 
}
interface Stack<E> << interface >>
class StackedArray<E> {
  + StackedArray(): 
  - data: ArrayList<E>
}
class StackedArrayTest {
  + StackedArrayTest(): 
}
class Teclado {
  + Teclado(): 
  ~ leer: Scanner
}
class Vista {
  + Vista(): 
  ~ leer: Scanner
  ~ in: Teclado
}
interface node1 as "package-info" << interface >>
interface node2 as "package-info" << interface >>
interface node13 as "package-info" << interface >>

Menu                            "1" *-[#595959,plain]-> "indexColors\n*" AnsiColors                      
Menu                            "1" *-[#595959,plain]-> "entries\n*" MenuEntry                       
MostrarMenu                     "1" *-[#595959,plain]-> "controlador\n1" Controller                      
MostrarMenu                     "1" *-[#595959,plain]-> "vista\n1" Vista                           
StackedArray                     -[#008200,dashed]-^  Stack                           
Vista                           "1" *-[#595959,plain]-> "in\n1" Teclado                         
@enduml
